swagger: '2.0'
info:
  description: 开心就好
  version: 1.0.0
  title: 小程序业务开发平台

basePath: /renren-fast

schemes:
  - http

#认证
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "token"
    in: "header"

#定义接口数据
paths:
  /business/appimages/list:
      get:
        tags:
          - 引用资源管理
        summary: 引用资源管理
        produces:
          - application/json
        parameters:
          - name: page
            description: 页码
            in: query
            type: integer
            required: true
          - name: limit
            description: 每页条数
            in: query
            type: integer
            required: true
          - name: sidx
            description: 排序字段
            in: query
            type: string
          - name: order
            description: 排序方式，如：asc、desc
            in: query
            type: string
          - name: token
            description: token
            in: query
            type: string
        responses:
          '200':
            description: 返回资源资源列表
            schema:
              $ref: '#/definitions/SysUserEntityList'

  /business/appnews/list:
        get:
          tags:
            -  新闻资源管理
          summary: 新闻资源管理
          produces:
            - application/json
          parameters:
            - name: page
              description: 页码
              in: query
              type: integer
              required: true
            - name: limit
              description: 每页条数
              in: query
              type: integer
              required: true
            - name: sidx
              description: 排序字段
              in: query
              type: string
            - name: order
              description: 排序方式，如：asc、desc
              in: query
              type: string
            - name: token
              description: token
              in: query
              type: string
          responses:
            '200':
              description: 返回资源资源列表
              schema:
                $ref: '#/definitions/SysUserEntityList'

#定义数据模型
definitions:
  R:
      type: object
      properties:
        code:
          description: 状态码 0：成功  非0：失败
          type: integer
          format: int32
        msg:
          description: 失败原因
          type: string
  SysUserEntityList:
      type: object
      properties:
        code:
          description: 状态码 0：成功  非0：失败
          type: integer
          format: int32
        page:
          type: object
          properties:
            totalCount:
              description: 总记录数
              type: integer
              format: int32
            pageSize:
              description: 每页记录数
              type: integer
              format: int32
            totalPage:
              description: 总页数
              type: integer
              format: int32
            currPage:
              description: 当前页数
              type: integer
              format: int32
            list:
              type: array
              items:
                $ref: '#/definitions/SysUserEntity'
  SysUserEntity:
      type: object
      properties:
        imageId:
          description: 图片ID
          type: integer
          format: int64
        url:
          description: 图片地址
          type: string
        message:
          description: 图片描述
          type: string
          
        type:
          description: 图片类型
          type: string
        createTime:
          description: 创建时间
          type: string
          format: date-time
        updateTime:
          description: 更新时间
          type: string
          format: date-time